# -*- coding: utf-8 -*-
"""trainModel.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17SBo7tq1P8-tDNFhu5zk9PH4bSSbCkMD
"""

import pandas as pd
import numpy as np
import joblib
import warnings
from sklearn.ensemble import RandomForestRegressor, IsolationForest
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score, accuracy_score, f1_score, classification_report
import matplotlib.pyplot as plt
import seaborn as sns

warnings.filterwarnings('ignore')
sns.set_style('whitegrid')

print("Libraries imported successfully!")

# Place this RIGHT AFTER your imports and BEFORE loading any CSV files

def encode_protocol_type(df):
    """Convert protocol_type from string to numeric encoding"""
    if 'protocol_type' not in df.columns:
        return df

    df = df.copy()

    def map_protocol(value):
        if isinstance(value, (int, float)) and not pd.isna(value):
            return int(value)

        value_str = str(value).upper().strip()

        if 'TCP' in value_str and 'UDP' not in value_str:
            return 1
        elif 'UDP' in value_str and 'TCP' not in value_str:
            return 2
        elif 'TCP/UDP' in value_str or 'UDP/TCP' in value_str:
            return 1
        elif 'ICMP' in value_str:
            return 3
        elif value_str == '6':
            return 1
        elif value_str == '17':
            return 2
        elif value_str == '1':
            return 3
        else:
            return 0

    df['protocol_type'] = df['protocol_type'].apply(map_protocol).astype(int)
    return df

print("Protocol encoding function defined!")

# Load ModelR datasets
print("Loading ModelR datasets...")

try:
    df_vnat = pd.read_csv('bandwidth_VNAT.csv')
    print(f"✓ Loaded bandwidth_VNAT.csv: {df_vnat.shape}")
    if not df_vnat.empty:
      df_vnat = encode_protocol_type(df_vnat)
      print(f"✓ Encoded protocol_type in VNAT dataset")
      print(f"  Unique values: {df_vnat['protocol_type'].unique()}")
except Exception as e:
    print(f"✗ Error loading bandwidth_VNAT.csv: {e}")
    df_vnat = pd.DataFrame()

try:
    df_generated_bw = pd.read_csv('bandwidth_generated.csv')
    print(f"✓ Loaded bandwidth_generated.csv: {df_generated_bw.shape}")
    if not df_generated_bw.empty:
      df_generated_bw = encode_protocol_type(df_generated_bw)
      print(f"✓ Encoded protocol_type in Generated Bandwidth dataset")
      print(f"  Unique values: {df_generated_bw['protocol_type'].unique()}")
except Exception as e:
    print(f"✗ Error loading bandwidth_generated.csv: {e}")
    df_generated_bw = pd.DataFrame()

# Display first few rows
if not df_vnat.empty:
    print("\nVNAT Dataset Sample:")
    display(df_vnat.head())
    print(f"\nMissing values:\n{df_vnat.isnull().sum()}")

# Load ModelA datasets
print("Loading ModelA datasets...")

try:
    df_cic = pd.read_csv('anomaly_CIC-IDS.csv')
    print(f"✓ Loaded anomaly_CIC-IDS.csv: {df_cic.shape}")
    if not df_cic.empty:
      df_cic = encode_protocol_type(df_cic)
      print(f"✓ Encoded protocol_type in CIC-IDS dataset")
      print(f"  Unique values: {df_cic['protocol_type'].unique()}")
except Exception as e:
    print(f"✗ Error loading anomaly_CIC-IDS.csv: {e}")
    df_cic = pd.DataFrame()

try:
    df_generated_anom = pd.read_csv('anomaly_generated.csv')
    print(f"✓ Loaded anomaly_generated.csv: {df_generated_anom.shape}")
    if not df_generated_anom.empty:
      df_generated_anom = encode_protocol_type(df_generated_anom)
      print(f"✓ Encoded protocol_type in Generated Anomaly dataset")
      print(f"  Unique values: {df_generated_anom['protocol_type'].unique()}")
except Exception as e:
    print(f"✗ Error loading anomaly_generated.csv: {e}")
    df_generated_anom = pd.DataFrame()

# Display first few rows
if not df_cic.empty:
    print("\nCIC-IDS Dataset Sample:")
    display(df_cic.head())
    print(f"\nMissing values:\n{df_cic.isnull().sum()}")

def clean_bandwidth_data(df, dataset_name=""):
    """
    Clean and prepare bandwidth prediction dataset (ModelR)
    """
    print(f"\nCleaning {dataset_name}...")
    df = df.copy()

    # Expected columns for ModelR
    expected_cols = ['mac_address', 'avg_packet_size', 'total_bytes', 'total_packets',
                     'flow_duration', 'bytes_per_second', 'packets_per_second',
                     'protocol_type', 'avg_inter_arrival_time', 'std_packet_size',
                     'unique_dst_ports', 'tcp_flag_ratio', 'payload_entropy',
                     'bidirectional_ratio', 'is_encrypted', 'time_of_day', 'bandwidth_kbps']

    # Keep only expected columns that exist
    available_cols = [col for col in expected_cols if col in df.columns]
    df = df[available_cols]

    print(f"  Initial shape: {df.shape}")

    # Encode protocol_type FIRST before other operations
    if 'protocol_type' in df.columns:
        df = encode_protocol_type(df)
        print(f"  Protocol types after encoding: {df['protocol_type'].unique()}")

    # Handle missing values
    numeric_cols = df.select_dtypes(include=[np.number]).columns
    for col in numeric_cols:
        if df[col].isnull().sum() > 0:
            df[col].fillna(df[col].median(), inplace=True)

    # Fill categorical missing values
    if 'mac_address' in df.columns:
        df['mac_address'].fillna('unknown', inplace=True)

    # Remove rows with infinite values
    df.replace([np.inf, -np.inf], np.nan, inplace=True)
    df.dropna(inplace=True)

    # Ensure target variable is positive
    if 'bandwidth_kbps' in df.columns:
        df = df[df['bandwidth_kbps'] > 0]

    print(f"  Final shape: {df.shape}")
    print(f"  Missing values: {df.isnull().sum().sum()}")

    return df


def clean_anomaly_data(df, dataset_name=""):
    """
    Clean and prepare anomaly detection dataset (ModelA)
    """
    print(f"\nCleaning {dataset_name}...")
    df = df.copy()

    # Expected columns for ModelA
    expected_cols = ['mac_address', 'total_bytes', 'total_packets', 'flow_duration',
                     'bytes_per_second', 'packets_per_second', 'avg_packet_size',
                     'std_packet_size', 'packet_size_variance', 'avg_inter_arrival_time',
                     'protocol_type', 'protocol_diversity', 'unique_dst_ports',
                     'unique_src_ports', 'is_encrypted', 'tcp_flag_ratio',
                     'payload_entropy', 'bidirectional_ratio', 'time_of_day',
                     'connection_rate', 'failed_connection_ratio', 'port_scan_indicator',
                     'is_anomaly']

    # Keep only expected columns that exist
    available_cols = [col for col in expected_cols if col in df.columns]
    df = df[available_cols]

    print(f"  Initial shape: {df.shape}")

    # Encode protocol_type FIRST before other operations
    if 'protocol_type' in df.columns:
        df = encode_protocol_type(df)
        print(f"  Protocol types after encoding: {df['protocol_type'].unique()}")

    # Drop columns that are entirely NaN
    cols_to_drop_due_to_all_nan = df.columns[df.isnull().all()].tolist()
    if cols_to_drop_due_to_all_nan:
        print(f"  Dropping entirely NaN columns: {cols_to_drop_due_to_all_nan}")
        df.drop(columns=cols_to_drop_due_to_all_nan, inplace=True)

    # Handle missing values for remaining columns
    numeric_cols = df.select_dtypes(include=[np.number]).columns
    for col in numeric_cols:
        if df[col].isnull().sum() > 0:
            df[col].fillna(df[col].median(), inplace=True)

    # Fill categorical missing values
    if 'mac_address' in df.columns:
        df['mac_address'].fillna('unknown', inplace=True)

    # Ensure is_anomaly is binary
    if 'is_anomaly' in df.columns:
        df['is_anomaly'] = df['is_anomaly'].astype(int)

    # Remove rows with infinite values
    df.replace([np.inf, -np.inf], np.nan, inplace=True)
    df.dropna(inplace=True)

    print(f"  Final shape: {df.shape}")
    print(f"  Missing values: {df.isnull().sum().sum()}")

    return df

print("Updated data preparation functions with protocol encoding!")

# Apply minor preparation for df_vnat
if not df_vnat.empty:
    df_vnat_prep = df_vnat.copy()
    df_vnat_prep.replace([np.inf, -np.inf], np.nan, inplace=True)
    df_vnat_prep.dropna(inplace=True)
    if 'bandwidth_kbps' in df_vnat_prep.columns:
        df_vnat_prep = df_vnat_prep[df_vnat_prep['bandwidth_kbps'] > 0]
    print(f"\nMinor preparation for VNAT Dataset: {df_vnat_prep.shape} (after filtering)")
else:
    df_vnat_prep = pd.DataFrame()

# Apply minor preparation for df_generated_bw
if not df_generated_bw.empty:
    df_generated_bw_prep = df_generated_bw.copy()
    df_generated_bw_prep.replace([np.inf, -np.inf], np.nan, inplace=True)
    df_generated_bw_prep.dropna(inplace=True)
    if 'bandwidth_kbps' in df_generated_bw_prep.columns:
        df_generated_bw_prep = df_generated_bw_prep[df_generated_bw_prep['bandwidth_kbps'] > 0]
    print(f"Minor preparation for Generated Bandwidth Dataset: {df_generated_bw_prep.shape} (after filtering)")
else:
    df_generated_bw_prep = pd.DataFrame()

# Combine datasets for ModelR
if not df_vnat_prep.empty and not df_generated_bw_prep.empty:
    df_modelr = pd.concat([df_vnat_prep, df_generated_bw_prep], ignore_index=True)
elif not df_vnat_prep.empty:
    df_modelr = df_vnat_prep
elif not df_generated_bw_prep.empty:
    df_modelr = df_generated_bw_prep
else:
    df_modelr = pd.DataFrame()

print(f"\n{'='*50}")
print(f"Combined ModelR Dataset Shape: {df_modelr.shape}")
print(f"{'='*50}")

if not df_modelr.empty:
    print("\nBandwidth Statistics:")
    print(df_modelr['bandwidth_kbps'].describe())

# Clean CIC-IDS dataset (messy data)
if not df_cic.empty:
    df_cic_clean = clean_anomaly_data(df_cic, "CIC-IDS Dataset")
else:
    df_cic_clean = pd.DataFrame()

# Clean generated anomaly dataset
if not df_generated_anom.empty:
    df_generated_anom_clean = clean_anomaly_data(df_generated_anom, "Generated Anomaly Dataset")
else:
    df_generated_anom_clean = pd.DataFrame()

# Combine datasets for ModelA
if not df_cic_clean.empty and not df_generated_anom_clean.empty:
    df_modela = pd.concat([df_cic_clean, df_generated_anom_clean], ignore_index=True)
elif not df_cic_clean.empty:
    df_modela = df_cic_clean
elif not df_generated_anom_clean.empty:
    df_modela = df_generated_anom_clean
else:
    df_modela = pd.DataFrame()

print(f"\n{'='*50}")
print(f"Combined ModelA Dataset Shape: {df_modela.shape}")
print(f"{'='*50}")

if not df_modela.empty and 'is_anomaly' in df_modela.columns:
    print("\nAnomaly Distribution:")
    print(df_modela['is_anomaly'].value_counts())
    print(f"\nAnomaly Rate: {df_modela['is_anomaly'].mean():.2%}")

# Replace the scaler fitting section in your trainModel.ipynb with this:

bandwidth_features = ['avg_packet_size', 'total_bytes', 'total_packets', 'flow_duration',
                      'bytes_per_second', 'packets_per_second', 'protocol_type',
                      'avg_inter_arrival_time', 'std_packet_size', 'unique_dst_ports',
                      'tcp_flag_ratio', 'payload_entropy', 'bidirectional_ratio',
                      'is_encrypted', 'time_of_day']

anomaly_features = ['avg_packet_size', 'total_bytes', 'total_packets', 'flow_duration',
                    'bytes_per_second', 'packets_per_second', 'protocol_type',
                    'avg_inter_arrival_time', 'std_packet_size', 'unique_dst_ports',
                    'tcp_flag_ratio', 'payload_entropy', 'bidirectional_ratio',
                    'is_encrypted', 'time_of_day', 'connection_rate',
                    'failed_connection_ratio', 'port_scan_indicator',
                    'packet_size_variance', 'protocol_diversity']

# IMPORTANT: protocol_type should NOT be scaled (it's categorical)
# Only scale numeric features
numeric_bandwidth_features = [f for f in bandwidth_features if f != 'protocol_type']
numeric_anomaly_features = [f for f in anomaly_features if f != 'protocol_type']

# --- Scaling for ModelR (Bandwidth Prediction) ---
print("\n--- Preparing features for ModelR (Bandwidth Prediction) ---")

if not df_modelr.empty and len(numeric_bandwidth_features) > 0:
    scaler_modelr = StandardScaler()
    # Select only the numeric features to scale for ModelR
    X_modelr_numeric = df_modelr[numeric_bandwidth_features]
    scaler_modelr.fit(X_modelr_numeric)
    print(f"✓ StandardScaler for ModelR fitted on {X_modelr_numeric.shape[0]} samples and {X_modelr_numeric.shape[1]} features.")
    print(f"  Features being scaled: {numeric_bandwidth_features}")
else:
    print("✗ No suitable features or data for ModelR scaling.")
    scaler_modelr = None

# --- Scaling for ModelA (Anomaly Detection) ---
print("\n--- Preparing features for ModelA (Anomaly Detection) ---")

if not df_modela.empty and len(numeric_anomaly_features) > 0:
    scaler_modela = StandardScaler()
    # Select only the numeric features to scale for ModelA
    X_modela_numeric = df_modela[numeric_anomaly_features]
    scaler_modela.fit(X_modela_numeric)
    print(f"✓ StandardScaler for ModelA fitted on {X_modela_numeric.shape[0]} samples and {X_modela_numeric.shape[1]} features.")
    print(f"  Features being scaled: {numeric_anomaly_features}")
else:
    print("✗ No suitable features or data for ModelA scaling.")
    scaler_modela = None

print("\nSeparate scalers created and fitted for ModelR and ModelA.")
print(f"\nModelR will scale {len(numeric_bandwidth_features)} features (excluding protocol_type)")
print(f"ModelA will scale {len(numeric_anomaly_features)} features (excluding protocol_type)")

# Replace the ModelR training section with this:

if not df_modelr.empty and 'bandwidth_kbps' in df_modelr.columns:
    print("Training ModelR (Bandwidth Predictor)...\n")

    # Prepare features - separate numeric and categorical
    numeric_cols = [f for f in bandwidth_features if f != 'protocol_type']

    # Get numeric features
    X_bw_numeric = df_modelr[numeric_cols].copy()

    # Get protocol_type separately (don't scale it)
    X_bw_protocol = df_modelr[['protocol_type']].copy()

    # Scale only numeric features
    X_bw_numeric_scaled = scaler_modelr.transform(X_bw_numeric)

    # Convert scaled array back to DataFrame to maintain feature names
    X_bw_numeric_scaled_df = pd.DataFrame(
        X_bw_numeric_scaled,
        columns=numeric_cols,
        index=X_bw_numeric.index
    )

    # Combine scaled numeric features with unscaled protocol_type
    X_bw_scaled = pd.concat([X_bw_numeric_scaled_df, X_bw_protocol], axis=1)

    # Reorder columns to match original bandwidth_features order
    X_bw_scaled = X_bw_scaled[bandwidth_features]

    y_bw = df_modelr['bandwidth_kbps']

    # Split data
    X_train, X_test, y_train, y_test = train_test_split(
        X_bw_scaled, y_bw, test_size=0.2, random_state=42
    )

    print(f"Training set: {X_train.shape[0]} samples")
    print(f"Test set: {X_test.shape[0]} samples")
    print(f"Features: {X_train.shape[1]} (including protocol_type)\n")

    # Train RandomForestRegressor
    model_r = RandomForestRegressor(
        n_estimators=100,
        max_depth=20,
        min_samples_split=5,
        min_samples_leaf=2,
        random_state=42,
        n_jobs=-1
    )

    model_r.fit(X_train, y_train)
    print("✓ Model training complete!\n")

    # Evaluate
    y_pred = model_r.predict(X_test)

    mse = mean_squared_error(y_test, y_pred)
    rmse = np.sqrt(mse)
    r2 = r2_score(y_test, y_pred)

    print("Model Performance:")
    print(f"  RMSE: {rmse:.2f} kbps")
    print(f"  R² Score: {r2:.4f}")
    print(f"  Mean Absolute Error: {np.mean(np.abs(y_test - y_pred)):.2f} kbps")

    # Feature importance
    feature_importance = pd.DataFrame({
        'feature': bandwidth_features,
        'importance': model_r.feature_importances_
    }).sort_values('importance', ascending=False)

    print("\nTop 10 Important Features:")
    print(feature_importance.head(10))

else:
    print("✗ Cannot train ModelR: No bandwidth data available")
    model_r = None

if model_r is not None:
    fig, axes = plt.subplots(1, 2, figsize=(14, 5))

    # Predicted vs Actual
    axes[0].scatter(y_test, y_pred, alpha=0.5)
    axes[0].plot([y_test.min(), y_test.max()], [y_test.min(), y_test.max()], 'r--', lw=2)
    axes[0].set_xlabel('Actual Bandwidth (kbps)')
    axes[0].set_ylabel('Predicted Bandwidth (kbps)')
    axes[0].set_title('Predicted vs Actual Bandwidth')
    axes[0].grid(True)

    # Residuals
    residuals = y_test - y_pred
    axes[1].hist(residuals, bins=50, edgecolor='black')
    axes[1].set_xlabel('Residual (kbps)')
    axes[1].set_ylabel('Frequency')
    axes[1].set_title('Prediction Residuals')
    axes[1].grid(True)

    plt.tight_layout()
    plt.show()

# Replace the ModelA training section with this:

if not df_modela.empty:
    print("Training ModelA (Anomaly Detector)...\n")

    # Prepare features - separate numeric and categorical
    numeric_cols = [f for f in anomaly_features if f != 'protocol_type']

    # Get numeric features
    X_anom_numeric = df_modela[numeric_cols].copy()

    # Get protocol_type separately (don't scale it)
    X_anom_protocol = df_modela[['protocol_type']].copy()

    # Scale only numeric features
    X_anom_numeric_scaled = scaler_modela.transform(X_anom_numeric)

    # Convert scaled array back to DataFrame
    X_anom_numeric_scaled_df = pd.DataFrame(
        X_anom_numeric_scaled,
        columns=numeric_cols,
        index=X_anom_numeric.index
    )

    # Combine scaled numeric features with unscaled protocol_type
    X_anom_scaled = pd.concat([X_anom_numeric_scaled_df, X_anom_protocol], axis=1)

    # Reorder columns to match original anomaly_features order
    X_anom_scaled = X_anom_scaled[anomaly_features]

    print(f"Training samples: {X_anom_scaled.shape[0]}")
    print(f"Features: {X_anom_scaled.shape[1]} (including protocol_type)\n")

    # Determine contamination rate from data
    if 'is_anomaly' in df_modela.columns:
        contamination = df_modela['is_anomaly'].mean()
        contamination = max(0.01, min(0.5, contamination))  # Clamp between 1% and 50%
    else:
        contamination = 0.1  # Default 10%

    print(f"Using contamination rate: {contamination:.2%}\n")

    # Train IsolationForest
    model_a = IsolationForest(
        n_estimators=100,
        max_samples='auto',
        contamination=contamination,
        random_state=42,
        n_jobs=-1
    )

    model_a.fit(X_anom_scaled)
    print("✓ Model training complete!\n")

    # Evaluate if labels are available
    if 'is_anomaly' in df_modela.columns:
        y_true = df_modela['is_anomaly']
        y_pred = model_a.predict(X_anom_scaled)
        y_pred_binary = (y_pred == -1).astype(int)  # Convert -1/1 to 0/1

        accuracy = accuracy_score(y_true, y_pred_binary)
        f1 = f1_score(y_true, y_pred_binary)

        print("Model Performance:")
        print(f"  Accuracy: {accuracy:.4f}")
        print(f"  F1 Score: {f1:.4f}")
        print(f"  Anomalies Detected: {y_pred_binary.sum()} / {len(y_pred_binary)}")
        print(f"  True Anomalies: {y_true.sum()}\n")

        print("Classification Report:")
        print(classification_report(y_true, y_pred_binary, target_names=['Normal', 'Anomaly']))

else:
    print("✗ Cannot train ModelA: No anomaly data available")
    model_a = None

"""# Task
Define a hyperparameter search space for the `IsolationForest` model (ModelA), including `n_estimators`, `max_samples`, and `contamination`. Then, implement an iterative evaluation process to tune ModelA by training and evaluating the model with each combination of hyperparameters, and identify the best-performing set of hyperparameters based on F1-score.

## Define Hyperparameter Search Space for ModelA

### Subtask:
Define a dictionary of hyperparameters and their potential values to search for the IsolationForest model (ModelA). This will include `n_estimators`, `max_samples`, and `contamination`.

**Reasoning**:
I need to define a dictionary for hyperparameter search space for ModelA as instructed, including `n_estimators`, `max_samples`, and `contamination` with their specified value ranges.
"""

param_grid_model_a = {
    'n_estimators': [50, 100, 200],
    'max_samples': ['auto', 0.5, 0.7],
    'contamination': [0.01, 0.05, 0.1, 0.2, 0.5]
}

print("Hyperparameter search space for ModelA defined:")
for param, values in param_grid_model_a.items():
    print(f"  {param}: {values}")

"""**Reasoning**:
Now that the hyperparameter search space is defined, I will implement an iterative evaluation process to tune ModelA by training and evaluating the model with each combination of hyperparameters. This process will identify the best-performing set of hyperparameters based on F1-score.


"""

from sklearn.model_selection import ParameterGrid

if not df_modela.empty:
    print("Tuning ModelA (Anomaly Detector) using IsolationForest...")

    # Prepare features and target (X_anom_scaled and y_true are already available)
    # X_anom_scaled was prepared previously.
    # y_true is df_modela['is_anomaly']

    best_f1_score = -1
    best_params = {}
    results = []

    param_combinations = ParameterGrid(param_grid_model_a)

    print(f"Total combinations to evaluate: {len(param_combinations)}\n")

    # Iterate over each combination of hyperparameters
    for i, params in enumerate(param_combinations):
        print(f"Evaluating combination {i+1}/{len(param_combinations)} with params: {params}")

        # Train IsolationForest with current hyperparameters
        model_a_tuned = IsolationForest(
            n_estimators=params['n_estimators'],
            max_samples=params['max_samples'],
            contamination=params['contamination'],
            random_state=42,
            n_jobs=-1
        )

        model_a_tuned.fit(X_anom_scaled)

        # Predict and evaluate
        y_pred = model_a_tuned.predict(X_anom_scaled)
        y_pred_binary = (y_pred == -1).astype(int)

        f1 = f1_score(y_true, y_pred_binary)
        accuracy = accuracy_score(y_true, y_pred_binary)

        results.append({
            'params': params,
            'f1_score': f1,
            'accuracy': accuracy
        })

        print(f"  F1 Score: {f1:.4f}, Accuracy: {accuracy:.4f}")

        # Update best parameters if current model is better
        if f1 > best_f1_score:
            best_f1_score = f1
            best_params = params
        print()

    print("\n--- Hyperparameter Tuning Complete ---")
    print(f"Best F1 Score: {best_f1_score:.4f}")
    print(f"Best Parameters: {best_params}")

else:
    print("✗ Cannot tune ModelA: No anomaly data available")

"""## Evaluate Tuned ModelA

### Subtask:
Evaluate the ModelA with the best-found hyperparameters on the entire dataset (or a dedicated test set if split) and display the accuracy, F1-score, and a classification report.

**Reasoning**:
I will initialize a new IsolationForest model using the `best_params` identified during hyperparameter tuning, train it on the scaled anomaly data, make predictions, convert them to binary labels, and then evaluate its performance by calculating and printing the accuracy, F1-score, and a comprehensive classification report.
"""

if not df_modela.empty and best_params:
    print("\n--- Evaluating Best Tuned ModelA (Anomaly Detector) ---\n")

    # 1. Initialize a new IsolationForest model with the best_params
    model_a_tuned_best = IsolationForest(
        n_estimators=best_params['n_estimators'],
        max_samples=best_params['max_samples'],
        contamination=best_params['contamination'],
        random_state=42,
        n_jobs=-1
    )

    # 2. Train model_a_tuned_best on the X_anom_scaled dataset
    model_a_tuned_best.fit(X_anom_scaled)
    print("✓ Best ModelA trained successfully with parameters:", best_params)

    # 3. Make predictions using the model_a_tuned_best on X_anom_scaled
    y_pred_best = model_a_tuned_best.predict(X_anom_scaled)

    # 4. Convert the predictions to binary labels (0 for normal, 1 for anomaly)
    #    -1 from IsolationForest output indicates an anomaly, 1 indicates normal
    y_pred_binary_best = (y_pred_best == -1).astype(int)

    # Ensure y_true is available (it should be from previous steps)
    if 'is_anomaly' in df_modela.columns:
        y_true_best = df_modela['is_anomaly']

        # 5. Calculate and print the accuracy score
        accuracy_best = accuracy_score(y_true_best, y_pred_binary_best)
        print(f"  Accuracy (Best Model): {accuracy_best:.4f}")

        # 6. Calculate and print the F1-score
        f1_best = f1_score(y_true_best, y_pred_binary_best)
        print(f"  F1 Score (Best Model): {f1_best:.4f}")

        # 7. Print a detailed classification report
        print("\nClassification Report (Best Model):")
        print(classification_report(y_true_best, y_pred_binary_best, target_names=['Normal', 'Anomaly']))
    else:
        print("✗ Target variable 'is_anomaly' not found in df_modela for evaluation.")

else:
    print("✗ Cannot evaluate best ModelA: No anomaly data or best parameters available")

"""## Final Task

### Subtask:
Summarize the hyperparameter tuning process for ModelA, highlight the best performing hyperparameters, and discuss the improvements or changes in model performance after tuning.

## Summary:

### Q&A
The hyperparameter tuning process for ModelA involved defining a search space for `n_estimators`, `max_samples`, and `contamination`, followed by an iterative evaluation of 45 combinations using the F1-score as the performance metric. The best-performing hyperparameters for ModelA (IsolationForest) were identified as `{'contamination': 0.5, 'max_samples': 'auto', 'n_estimators': 50}`, achieving an F1-score of 0.5664. After tuning, the model performance was evaluated, yielding an accuracy of 0.5653 and an F1-score of 0.5664. The classification report showed comparable performance for both 'Normal' and 'Anomaly' classes, with F1-scores of 0.56 and 0.57 respectively.

### Data Analysis Key Findings
*   A hyperparameter search space was defined for ModelA (IsolationForest) including `n_estimators` (50, 100, 200), `max_samples` ('auto', 0.5, 0.7), and `contamination` (0.01, 0.05, 0.1, 0.2, 0.5), resulting in 45 unique combinations.
*   The best performing set of hyperparameters found during the tuning process was `{'contamination': 0.5, 'max_samples': 'auto', 'n_estimators': 50}`.
*   The maximum F1-score achieved during hyperparameter tuning for ModelA was 0.5664.
*   The best-tuned ModelA achieved an overall accuracy of 0.5653 and an F1-score of 0.5664 on the dataset.
*   The classification report for the best-tuned model showed an F1-score of 0.56 for the 'Normal' class and 0.57 for the 'Anomaly' class.

### Insights or Next Steps
*   The F1-score of approximately 0.57 indicates that while the model has some capability in detecting anomalies, there is significant room for improvement. This might suggest the need for more sophisticated anomaly detection algorithms or feature engineering.
*   Given the relatively balanced performance between 'Normal' and 'Anomaly' classes, further investigation into the nature of anomalies and potential class imbalance (if not already addressed) could be beneficial. Considering different evaluation metrics like Precision-Recall AUC, especially for imbalanced datasets, might also provide a more nuanced view of the model's performance.

# Task
Perform hyperparameter tuning for the RandomForestRegressor model (ModelR) by defining a search space, iteratively evaluating different hyperparameter combinations, and then summarizing the tuning process and the impact on model performance.

## Define Hyperparameter Search Space for ModelR

### Subtask:
Define a dictionary of hyperparameters and their potential values to search for the RandomForestRegressor model (ModelR). This will include `n_estimators`, `max_depth`, `min_samples_split`, and `min_samples_leaf`.

**Reasoning**:
I need to define a dictionary named `param_grid_model_r` containing the specified hyperparameters and their values for the RandomForestRegressor model (ModelR), as per the instructions.
"""

param_grid_model_r = {
    'n_estimators': [50, 100, 200],
    'max_depth': [10, 20, None],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4]
}

print("Hyperparameter search space for ModelR defined:")
for param, values in param_grid_model_r.items():
    print(f"  {param}: {values}")

"""## Tune ModelR with Iterative Evaluation

### Subtask:
Implement a loop to iterate through the defined hyperparameter combinations. For each combination, train a RandomForestRegressor model on the scaled ModelR training data, make predictions on the test set, and evaluate its performance using RMSE and R-squared. Track the best hyperparameters and the corresponding best model.

**Reasoning**:
I need to implement a loop to iterate through the defined hyperparameter combinations for ModelR. This involves training the model, making predictions, calculating RMSE and R-squared for each combination, and tracking the best-performing hyperparameters. The necessary variables like `X_train`, `X_test`, `y_train`, `y_test`, and `param_grid_model_r` are already available from previous steps.
"""

from sklearn.model_selection import ParameterGrid

if not df_modelr.empty:
    print("Tuning ModelR (Bandwidth Predictor) using RandomForestRegressor...")

    # Initialize variables to track the best model
    best_rmse = float('inf')
    best_r2_score = float('-inf')
    best_params = {}
    results_modelr = [] # Use a distinct name for results list

    # Create all hyperparameter combinations
    param_combinations_modelr = ParameterGrid(param_grid_model_r)

    print(f"Total combinations to evaluate: {len(param_combinations_modelr)}\n")

    # Iterate over each combination of hyperparameters
    for i, params in enumerate(param_combinations_modelr):
        print(f"Evaluating combination {i+1}/{len(param_combinations_modelr)} with params: {params}")

        # Train RandomForestRegressor with current hyperparameters
        model_r_tuned = RandomForestRegressor(
            n_estimators=params['n_estimators'],
            max_depth=params['max_depth'],
            min_samples_split=params['min_samples_split'],
            min_samples_leaf=params['min_samples_leaf'],
            random_state=42,
            n_jobs=-1
        )

        model_r_tuned.fit(X_train, y_train)

        # Make predictions
        y_pred_tuned = model_r_tuned.predict(X_test)

        # Evaluate
        rmse_tuned = np.sqrt(mean_squared_error(y_test, y_pred_tuned))
        r2_tuned = r2_score(y_test, y_pred_tuned)

        results_modelr.append({
            'params': params,
            'rmse': rmse_tuned,
            'r2_score': r2_tuned
        })

        print(f"  RMSE: {rmse_tuned:.2f} kbps, R\u00b2 Score: {r2_tuned:.4f}")

        # Update best parameters if current model is better (lower RMSE)
        if rmse_tuned < best_rmse:
            best_rmse = rmse_tuned
            best_r2_score = r2_tuned
            best_params = params
        print()

    print("\n--- Hyperparameter Tuning Complete for ModelR ---")
    print(f"Best RMSE: {best_rmse:.2f} kbps")
    print(f"Best R\u00b2 Score: {best_r2_score:.4f}")
    print(f"Best Parameters: {best_params}")

else:
    print("✗ Cannot tune ModelR: No bandwidth data available")

"""## Summary of Hyperparameter Tuning for ModelA

The hyperparameter tuning process for ModelA (IsolationForest) involved systematically evaluating various combinations of `n_estimators`, `max_samples`, and `contamination` within a predefined search space. A total of 45 unique hyperparameter combinations were explored.

**Best Performing Hyperparameters:**
The best performing set of hyperparameters identified was:
`{'contamination': 0.5, 'max_samples': 'auto', 'n_estimators': 50}`

**Model Performance After Tuning:**
Before tuning, the initial IsolationForest model trained with default `contamination` (derived from the data's anomaly rate of 50.26%) achieved an F1-score of **0.5432** and an accuracy of **0.5421**.

After hyperparameter tuning, the ModelA with the best-found parameters demonstrated the following performance:
- **F1 Score:** 0.5664
- **Accuracy:** 0.5653

**Improvements and Changes:**
The tuning process resulted in a modest improvement in ModelA's performance. The F1-score increased from approximately 0.5432 to 0.5664, and accuracy similarly improved. While these gains are not substantial, they indicate that the selected hyperparameters for the IsolationForest model lead to a slightly better balance between precision and recall in detecting anomalies. The classification report for the best-tuned model showed F1-scores of 0.56 for the 'Normal' class and 0.57 for the 'Anomaly' class, suggesting a relatively balanced performance in identifying both normal and anomalous instances. This improvement suggests that tailoring the IsolationForest's parameters to the specific dataset can yield better anomaly detection capabilities compared to using default or less optimized settings.

## Summary of Hyperparameter Tuning for ModelR

The hyperparameter tuning process for ModelR (RandomForestRegressor) involved systematically evaluating various combinations of `n_estimators`, `max_depth`, `min_samples_split`, and `min_samples_leaf` within a predefined search space. A total of 81 unique hyperparameter combinations were explored using a grid search approach.

**Best Performing Hyperparameters:**
The best performing set of hyperparameters identified was:
`{'max_depth': 10, 'min_samples_leaf': 1, 'min_samples_split': 2, 'n_estimators': 100}`

**Model Performance Comparison:**
- **Initial ModelR (before tuning):**
  - RMSE: 4659.80 kbps
  - R² Score: 0.5205

- **Best Tuned ModelR (after tuning):**
  - Best RMSE: 2624.85 kbps
  - Best R² Score: 0.8479

**Improvements and Changes:**
The hyperparameter tuning process significantly improved ModelR's performance. The Root Mean Squared Error (RMSE) was reduced from 4659.80 kbps to 2624.85 kbps, indicating a substantial decrease in the average magnitude of prediction errors. Concurrently, the R-squared score, which represents the proportion of variance in the dependent variable that is predictable from the independent variables, increased from 0.5205 to 0.8479. This demonstrates that the tuned model is much better at explaining the variability in bandwidth predictions and provides a more accurate forecast. The optimal parameters suggest that a `max_depth` of 10, `min_samples_leaf` of 1, `min_samples_split` of 2, and `n_estimators` of 100 resulted in a model that generalized well to the test data, achieving a much stronger predictive capability for bandwidth.

## Evaluate Tuned ModelR

### Subtask:
Evaluate the ModelR with the best-found hyperparameters on the dedicated test set and display the RMSE, R-squared score, and Mean Absolute Error.

**Reasoning**:
I will initialize a new RandomForestRegressor model with the best hyperparameters found during tuning, train it on the training data, and then evaluate its performance on the test set by calculating and displaying RMSE, R-squared, and Mean Absolute Error.
"""

if not df_modelr.empty and best_params:
    print("\n--- Evaluating Best Tuned ModelR (Bandwidth Predictor) ---\n")

    # 1. Initialize a new RandomForestRegressor model with the best_params
    model_r_tuned_best = RandomForestRegressor(
        n_estimators=best_params['n_estimators'],
        max_depth=best_params['max_depth'],
        min_samples_split=best_params['min_samples_split'],
        min_samples_leaf=best_params['min_samples_leaf'],
        random_state=42,
        n_jobs=-1
    )

    # 2. Train this new model on the scaled training data (X_train, y_train)
    model_r_tuned_best.fit(X_train, y_train)
    print("✓ Best ModelR trained successfully with parameters:", best_params)

    # 3. Make predictions on the scaled test data (X_test)
    y_pred_best_modelr = model_r_tuned_best.predict(X_test)

    # 4. Calculate Mean Squared Error (MSE)
    mse_best = mean_squared_error(y_test, y_pred_best_modelr)

    # 5. Calculate Root Mean Squared Error (RMSE)
    rmse_best = np.sqrt(mse_best)

    # 6. Calculate R-squared score
    r2_best = r2_score(y_test, y_pred_best_modelr)

    # 7. Calculate Mean Absolute Error (MAE)
    mae_best = np.mean(np.abs(y_test - y_pred_best_modelr))

    # 8. Print the calculated metrics
    print("\nBest Tuned ModelR Performance:")
    print(f"  RMSE: {rmse_best:.2f} kbps")
    print(f"  R\u00b2 Score: {r2_best:.4f}")
    print(f"  Mean Absolute Error: {mae_best:.2f} kbps")

else:
    print("✗ Cannot evaluate best ModelR: No bandwidth data or best parameters available")

"""## Final Task

### Subtask:
Summarize the hyperparameter tuning process for ModelR, highlight the best performing hyperparameters, and discuss the improvements or changes in model performance after tuning.

## Summary:

### Q&A
The hyperparameter tuning process for ModelR involved systematically evaluating 81 different combinations of `n_estimators`, `max_depth`, `min_samples_split`, and `min_samples_leaf` using a grid search approach. For each combination, a `RandomForestRegressor` model was trained and evaluated using RMSE and R-squared metrics. The best combination was selected based on the lowest RMSE.

The best performing hyperparameters for ModelR were identified as: `{'max_depth': 10, 'min_samples_leaf': 1, 'min_samples_split': 2, 'n_estimators': 100}`.

The tuning process led to a significant improvement in ModelR's performance. The Root Mean Squared Error (RMSE) was substantially reduced from 4659.80 kbps (initial model) to 2624.85 kbps (tuned model), representing a decrease of approximately 43.7%. Concurrently, the R-squared score increased from 0.5205 to 0.8479, indicating a much better fit to the data and improved predictive capability.

### Data Analysis Key Findings
*   A hyperparameter search space for ModelR (RandomForestRegressor) was defined, including `n_estimators` ([50, 100, 200]), `max_depth` ([10, 20, None]), `min_samples_split` ([2, 5, 10]), and `min_samples_leaf` ([1, 2, 4]), leading to 81 unique combinations.
*   The best performing hyperparameters identified for ModelR were `max_depth: 10`, `min_samples_leaf: 1`, `min_samples_split: 2`, and `n_estimators: 100`.
*   Before tuning, the initial ModelR had an RMSE of 4659.80 kbps and an R² score of 0.5205.
*   After tuning, the best ModelR achieved an RMSE of 2624.85 kbps, an R² score of 0.8479, and a Mean Absolute Error of 286.05 kbps.
*   The hyperparameter tuning resulted in a significant reduction in RMSE by 43.7% and an increase in R² score by 62.9%, indicating a substantial improvement in prediction accuracy and explanatory power.

### Insights or Next Steps
*   The substantial improvement in ModelR's performance after hyperparameter tuning (RMSE reduction from 4659.80 to 2624.85 kbps, R² increase from 0.5205 to 0.8479) demonstrates the critical importance of optimizing model parameters for predictive accuracy in bandwidth forecasting.
*   Further exploration could involve a wider range or finer grid for the identified optimal hyperparameters (e.g., `n_estimators` around 100, `max_depth` around 10) to potentially eke out even marginal performance gains, or using more advanced tuning techniques like Randomized Search or Bayesian Optimization for efficiency.
"""

import os

# Create a directory to save models if it doesn't exist
models_dir = '/content/models'
os.makedirs(models_dir, exist_ok=True)
print(f"Created directory: {models_dir}")

# Save the fitted StandardScaler for ModelR (bandwidth_scaler)
if 'scaler_modelr' in locals() and scaler_modelr is not None:
    joblib.dump(scaler_modelr, os.path.join(models_dir, 'bandwidth_scaler.pkl'))
    print(f"Bandwidth scaler saved to {os.path.join(models_dir, 'bandwidth_scaler.pkl')}")
else:
    print("ModelR scaler object not found or is None.")

# Save the fitted StandardScaler for ModelA (anomaly_scaler)
if 'scaler_modela' in locals() and scaler_modela is not None:
    joblib.dump(scaler_modela, os.path.join(models_dir, 'anomaly_scaler.pkl'))
    print(f"Anomaly scaler saved to {os.path.join(models_dir, 'anomaly_scaler.pkl')}")
else:
    print("ModelA scaler object not found or is None.")

# Save the trained bandwidth predictor (ModelR)
if 'model_r' in locals() and model_r is not None:
    joblib.dump(model_r, os.path.join(models_dir, 'bandwidth_predictor.pkl'))
    print(f"Bandwidth predictor saved to {os.path.join(models_dir, 'bandwidth_predictor.pkl')}")
else:
    print("Bandwidth predictor model (model_r) not found or is None.")

# Save the trained anomaly detector (ModelA)
if 'model_a' in locals() and model_a is not None:
    joblib.dump(model_a, os.path.join(models_dir, 'anomaly_detector.pkl'))
    print(f"Anomaly detector saved to {os.path.join(models_dir, 'anomaly_detector.pkl')}")
else:
    print("Anomaly detector model (model_a) not found or is None.")

from google.colab import files
files.download('/content/models/bandwidth_scaler.pkl')
files.download('/content/models/anomaly_scaler.pkl')
files.download('/content/models/anomaly_detector.pkl')
files.download('/content/models/bandwidth_predictor.pkl')